name: real_estate_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: 0.19.0
  gradient_borders: ^1.0.1
  shared_preferences: ^2.5.1
  connectivity_plus: ^6.1.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  country_pickers: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

