version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build: .
    container_name: flutter-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_HOST: postgres
      DB_NAME: yourdatabase
      DB_PORT: 5432
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
